version: 0.0
os: linux

files:
  - source: /
    destination: /home/root/app
    overwrite: yes

permissions:
  - object: /home/root/app
    owner: root
    group: root
    mode: 755

hooks:
  BeforeInstall:
    - location: scripts/stop.sh
      timeout: 60
      runas: root

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
