version: '3'
services:
  frontend:
    build: .
    container_name: nextjs-green
    networks:
      - frontend
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3002:3000"

networks:
  frontend:
    driver: bridge
