# blue
version: '3'
services:
  # 서비스의 이름
  frontend:
    # 현재 디렉토리에서의 Dockerfile을 사용하여 Docker 이미지를 빌드
    build: .
    container_name: nextjs-blue
    networks:
      - frontend
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "3001:3000"
    # 컨테이너의 이름
networks:
  frontend:
    driver: bridge