# 실행 시기
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# 작업 내용
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. GitHub 저장소 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. AWS 연결 (ECR)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login \
          --username AWS \
          --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com

      # 3. Docker 이미지 빌드 및 푸쉬
      - name: Build and Push Docker Image
        run: |
          docker build -f docker/Dockerfile -t frontend-prod .
          docker tag frontend-prod:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-prod:latest
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-prod:latest

      # 4. 쉘 스크립트 실행 권한 부여
      - name: Set execute permissions
        run: chmod +x scripts/*.sh

      # 5. ZIP 파일 생성
      - name: Create ZIP
        run: |
          mkdir deploy
          cp -r scripts deploy/
          cp appspec.yml deploy/
          zip -r -qq ./deploy-front.zip ./deploy

      # 6. S3에 ZIP 파일 업로드
      - name: Upload ZIP to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./deploy-front.zip s3://250325-ktblily-bucket-prod/deploy-front.zip

      # 7. AWS CodeDeploy 배포 요청
      - name: Deploy to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name frontend-app-prod \
            --deployment-group-name frontend-group-prod \
            --s3-location bucket=250325-ktblily-bucket-prod,bundleType=zip,key=deploy-front.zip \
            --file-exists-behavior OVERWRITE \
            --region ap-northeast-2