name: CI/CD for Next.js

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if secrets are set
        run: |
          if [[ -z "${{ secrets.DOCKER_USERNAME }}" ]]; then
            echo "❌ ERROR: DOCKER_USERNAME is not set!"
            exit 1
          fi

          if [[ -z "${{ secrets.DOCKER_PASSWORD }}" ]]; then
            echo "❌ ERROR: DOCKER_PASSWORD is not set!"
            exit 1
          fi

          echo "✅ All required secrets are set!"

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker build & push to DockerHub
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --cache-from=type=registry,ref=${{ secrets.DOCKERHUB_REPO }}/frontend:cache \
            --cache-to=type=registry,ref=${{ secrets.DOCKERHUB_REPO }}/frontend:cache,mode=max \
            -t ${{ secrets.DOCKERHUB_REPO }}/frontend:latest \
            --push .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        id: deploy
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Stopping existing frontend container..."
            docker-compose stop frontend
            
            echo "Updating .GCP_STT_KEY file..."
            echo "${{ secrets.ENV }}" > .env
            echo "${{ secrets.GCP_STT_KEY }}" > .gcp-stt-key.json

            
            echo "Pulling latest image..."
            docker pull ${{ secrets.DOCKERHUB_REPO }}/frontend:latest
            
            echo "Restarting frontend services..."
            docker-compose up -d frontend

            echo "Waiting for Next.js to start..."
            sleep 10
