# 실행 시기
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# 작업 내용
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. GitHub 저장소 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. ZIP 파일 생성 (빌드 없이 코드만 압축)
      - name: Create Deployment ZIP
        run: |
          mkdir deploy
          cp -r docker deploy/
          cp -r public deploy/
          cp -r scripts deploy/
          cp -r src deploy/
          cp .gitignore deploy/
          cp appspec.yml deploy/
          cp next.config.ts deploy/
          cp package.json deploy/
          cp package-lock.json deploy/
          cp postcss.config.mjs deploy/
          cp tailwind.config.ts deploy/
          cp tsconfig.json deploy/
          zip -r -qq ./nextjs-build.zip ./deploy

      # 3. AWS 연결
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 4. S3에 ZIP 파일 업로드
      - name: Upload ZIP to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./nextjs-build.zip s3://codedeploy-7week-lily/nextjs-build.zip

      # 5. AWS CodeDeploy 배포 요청
      - name: Deploy to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name codedeploy-web-7week \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name codedeploy-web-7week-group \
            --s3-location bucket=codedeploy-7week-lily,bundleType=zip,key=nextjs-build.zip